---
functional:
  - На сайте должен быть доступен демо-режим (регистрация не требуется, возможно пройти игру с ботом в качестве соперника, задание выдается рандомно)
  - На сайте должна быть возможность создать аккаунт для полного доступа к ресурсам
  - Форма регистрации должна содержать подсказки по заполнению полей (какие символы и в каком количестве могут использоваться + проверка занятости Nickname + проверка валидности email) и предлагать альтернативные варианты входа в систему (Github, Discord)
  - Форма авторизации должна быть с функцией восстановления забытого пароля
  - Авторизованному пользователю должны быть доступны: создание игры, список находящихся онлайн игроков, просмотр рейтинга игроков, просмотр истории завершенных игр, создание задания, чат, настройки собственного профиля (имя, звуковое оформление, язык программирования)
  - При создании игры можно выбрать сценарий: с ботом, с другом, с произвольным игроком
  - При создании игры можно выбрать уровень сложности: elementary, easy, medium, hard
  - При создании игры можно установить ограничение по времени прохождения (от 8 до 60 минут)
  - Задание для игры можно выбрать из выпадающего списка (доступен поиск по вводимым символам)
  - Должно отображаться уведомление о приглашении в игру у вызывающего и вызываемого игрока
  - Созданная игра должна отображать: поле с описанием задачи, два поля написания кода (игроки могут видеть написание кода друг друга), таймер, чат
  - Завершение игры сопровождается появлением соответствующей анимации у проигравшего и у победителя
  - Завершенная по тайм-ауту игра без победителя не отображается в истории
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть способен обрабатывать большое количество трафика (1000 одновременных пользователей)
  - Сайт должен быть совместим с последними версиями браузеров
  - Должна быть мобильная версия сайта
implicit:
  - На главной странице сайта должна быть предоставлена основная информация о проекте (правила участия, доступные игровые форматы, комментарии, создатели и т.п.)
  - У пользователя должна быть возможность удалить собственный аккаунт
